
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[436] =
    {   0,
        0,    0,  100,   98,   96,   96,   97,   84,   98,   98,
       90,   83,   98,   78,   79,   88,   87,   75,   86,   82,
       89,   45,   45,   76,   72,   91,   77,   92,   95,   39,
       39,   39,   39,   39,   39,   80,   81,   93,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   73,   94,   74,
       85,   71,    0,   50,    0,   41,   41,   57,   66,   58,
        0,    0,   55,   63,   53,   64,   54,   65,   48,    2,
       56,   49,   44,    0,   45,    0,   45,   62,   68,    0,
       70,   69,   61,   39,   39,   39,   39,   39,   39,   59,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   14,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   22,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   60,
       67,   41,   41,   46,    0,   48,   48,    0,   49,   44,
        0,   47,   43,   52,    0,    0,   51,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   20,   39,   39,   39,

       39,   39,   23,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   41,    0,   48,
        0,   48,    0,   49,   47,   43,    0,   39,   39,   38,
       39,   39,   39,   39,   39,   39,   39,   39,   39,    5,
       39,   39,    9,   10,   39,   39,   39,   39,   39,   16,
       17,   39,   39,   39,   39,   21,   39,   39,   24,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   36,   39,
       39,   39,   41,    0,   48,   42,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,    8,   39,   11,   39,
       39,   39,   39,   19,   39,   39,   39,   39,   39,   39,
       39,    7,   39,   39,   39,   39,   39,    4,   39,   27,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   34,   39,   39,    1,   41,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   15,   18,   39,   39,    3,   39,   39,   26,
       28,    6,   29,   39,   30,   39,   39,   31,   32,   39,

       39,   39,   40,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   13,   39,   33,   39,   39,   39,   39,
       39,   12,   25,   35,   37,   39,   39,   39,   39,   39,
       39,   39,   39,   39,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   36,   37,   34,   38,   39,   34,
       34,   40,   41,   42,   43,   34,   44,   45,   46,   34,
       47,   48,   49,   50,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   34,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        1,    1,    5,    5,    1,    1,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1,
        7,    6,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[444] =
    {   0,
        0,    0,  637,  638,  638,  638,  638,  612,   75,  580,
      610,   73,  585,  638,  638,  608,   69,  638,   70,   65,
       74,   71,   87,  638,  638,   76,  607,   85,  638,    0,
      599,  584,  585,  576,  595,  638,  638,  601,  573,   51,
       35,   73,   49,   63,   81,  557,   81,   23,   61,   74,
       84,   99,  100,   97,  557,  555,   94,  638,   88,  638,
      638,  638,  123,  638,  617,    0,  563,  638,  638,  638,
      151,  164,  638,  638,  638,  638,  638,  638,  144,  638,
      638,  158,  166,  168,  155,    0,  193,  594,  638,  600,
      638,  638,  592,    0,  587,  579,  576,  162,  581,  638,

      179,  553,  541,  543,  538,  541,  550,  154,  553,  538,
      538,  545,  530,  531,  528,  165,  535,  531,  528,  527,
      538,  523,  173,  522,  526,  534,  133,  525,  531,  531,
      518,  525,  519,  175,  531,  124,  516,  174,  529,  520,
      179,  519,  514,  506,  509,  179,  145,  515,  514,  638,
      638,    0,  516,  638,  238,  638,  240,  247,  638,  231,
      200,  250,  238,  638,  513,  554,  638,  527,  527,  531,
      527,  536,  525,  524,  527,  208,  527,  190,  505,  216,
      494,  496,  506,  494,  500,  487,  485,  171,  501,  499,
      495,  486,  479,  492,  478,  494,    0,  485,  488,  477,

      486,  486,    0,  482,  483,  473,  474,   42,  485,  470,
      466,  468,  477,  223,  471,  459,  464,  466,  466,  458,
      460,  468,  458,  446,  451,  186,  235,  450,  463,  462,
      461,  450,  455,  459,  461,  449,  441,  450,  260,  291,
      298,  638,  264,  300,  638,  278,  484,  475,  456,    0,
      475,  466,  461,  464,  451,  464,  462,  461,  430,    0,
      435,  430,    0,    0,  439,  424,  433,  421,  428,    0,
        0,  422,  433,  418,  422,    0,  429,  429,  423,  421,
      416,  414,  424,  409,  412,  407,  413,  406,  406,  416,
      408,  401,  414,  242,  414,  412,  407,  398,  400,  221,

      408,  409,  396,  407,  406,  404,  393,  399,    0,  386,
      399,  398,  388,  271,  307,  638,  263,  425,  413,  412,
      411,  224,  417,  418,  415,  375,    0,  390,    0,  378,
      379,  385,  375,    0,  369,    0,  381,  373,  382,  360,
      364,    0,  365,  375,  365,  360,  364,    0,  361,    0,
      372,  356,  368,  373,  369,  354,  354,  345,  354,  258,
      355,  347,  357,  359,    0,  349,  353,    0,  356,  384,
      367,  367,  371,  378,  369,  365,  368,  344,  349,  330,
      298,  298,    0,    0,  310,  299,    0,  311,  306,    0,
        0,    0,    0,  291,    0,  293,  284,    0,    0,  301,

      300,  292,    0,  318,  323,  305,  304,  317,  304,  294,
      308,  291,  284,    0,  270,    0,  281,  279,  297,  304,
      292,    0,    0,    0,    0,  287,  298,  286,  276,  258,
      241,  222,  138,   84,  638,  370,  372,  379,  382,  386,
      390,  394,  398
    } ;

static yyconst flex_int16_t yy_def[444] =
    {   0,
      435,    1,  435,  435,  435,  435,  435,  435,  436,  437,
      435,  435,  438,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  439,  435,  435,  435,  440,
      440,  440,  440,  440,  440,  435,  435,  435,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  435,  435,  435,
      435,  435,  436,  435,  436,  441,  441,  435,  435,  435,
      438,  438,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  442,  435,  435,  435,  443,
      435,  435,  435,  440,  440,  440,  440,  440,  440,  435,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  435,
      435,  441,  441,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  442,  435,  435,  443,  435,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  441,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  441,  435,  435,  435,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  441,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,

      440,  440,  441,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  440,  440,    0,  435,  435,  435,  435,  435,
      435,  435,  435
    } ;

static yyconst flex_int16_t yy_nxt[719] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   30,   31,
       32,   30,   30,   30,   30,   30,   30,   33,   34,   30,
       35,   30,   30,   30,   30,   30,   36,    4,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   30,   47,
       30,   30,   48,   49,   30,   50,   51,   52,   53,   54,
       55,   56,   57,   30,   30,   30,   58,   59,   60,   61,
       64,   69,   74,   79,   79,   76,   80,   82,  125,   83,
       83,  126,   75,   77,   78,  282,   70,   81,   88,   89,

      106,   84,  107,   82,  112,   87,   87,   85,   92,   93,
      283,  150,  127,   85,  113,   86,  128,   84,  102,  103,
      104,  105,   65,   85,  108,  114,   84,  115,   64,   85,
      129,  109,  117,   85,  250,  110,  116,  123,  111,  131,
      130,   85,   84,  118,   86,  124,  119,  120,  121,   85,
      133,  132,  148,  135,  134,  136,  143,   85,  137,  138,
      154,  149,   79,   79,  144,  151,  435,  139,  140,  141,
       65,  145,  142,   71,  155,  156,  157,  157,  250,  218,
      156,  161,   82,  161,   83,   83,  162,  162,  158,  159,
      171,   85,  206,  219,  159,  207,   84,   85,   72,  155,

      156,  172,  160,  173,  234,  174,  156,  235,  160,   82,
      176,   87,   87,  158,  159,  177,  184,   85,  162,  162,
      159,   84,  185,   84,  193,   85,  214,  201,  160,   85,
      225,  221,  215,  226,  194,   85,  160,  202,  232,  266,
      267,  298,  256,  250,  216,  299,  227,  233,   84,  222,
      257,  239,  250,  239,  376,   85,  240,  240,  157,  157,
      243,  250,  243,   85,  377,  244,  244,  160,  162,  162,
      241,  242,  250,  160,  246,  250,  242,  250,  240,  240,
      246,  245,  244,  244,  357,  287,  245,  358,  300,  315,
      315,  434,  352,  160,  370,  241,  242,  301,  433,  302,

      246,  160,  242,  371,  303,  304,  245,  353,  246,  240,
      240,  314,  245,  314,  246,  432,  315,  315,  244,  244,
      246,  396,  156,  431,  397,  315,  315,  156,  430,  429,
      428,  159,  427,  426,  425,  424,  159,  423,  242,  422,
      246,  250,  421,  242,  250,  250,  250,  156,  246,  250,
      250,  420,  419,  156,  418,  417,  159,  416,  250,  250,
      250,  415,  159,  242,  250,  250,  250,  414,  413,  242,
       63,   63,   63,   63,   63,   63,   63,   66,   66,   71,
      412,   71,   71,   71,   71,   71,   90,   90,   90,   94,
      411,   94,   94,  152,  410,  152,  152,  163,  409,  163,

      166,  166,  408,  166,  166,  407,  250,  406,  250,  405,
      404,  403,  402,  401,  400,  399,  398,  250,  250,  250,
      250,  250,  395,  394,  393,  392,  391,  250,  390,  389,
      388,  387,  250,  250,  250,  250,  386,  336,  385,  384,
      383,  382,  381,  250,  250,  380,  379,  378,  375,  374,
      373,  372,  369,  250,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  250,  356,  355,  354,  250,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  250,  338,  337,  336,  335,  334,  250,  333,
      332,  331,  330,  329,  250,  328,  327,  326,  325,  324,

      323,  322,  321,  320,  319,  318,  317,  250,  316,  313,
      312,  311,  310,  309,  308,  307,  306,  250,  250,  305,
      297,  296,  295,  294,  293,  292,  291,  250,  290,  289,
      288,  250,  286,  285,  250,  284,  281,  250,  280,  279,
      278,  277,  276,  250,  275,  274,  273,  272,  250,  271,
      270,  269,  268,  265,  264,  263,  262,  261,  250,  260,
      259,  258,  255,  254,  253,  252,  251,  250,  249,  248,
      165,  247,  238,  237,  236,  231,  230,  229,  228,  224,
      223,  220,  217,  213,  212,  211,  210,  209,  208,  205,
      204,  203,  200,  199,  198,  197,  196,  195,  192,  191,

      190,  189,  188,  187,  186,  183,  182,  181,  180,  179,
      178,  175,  170,  169,  168,  167,  165,  164,  153,  435,
      147,  146,  122,  101,  100,   99,   98,   97,   96,   95,
       91,   73,   72,   68,   67,   62,  435,    3,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435
    } ;

static yyconst flex_int16_t yy_chk[719] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   12,   17,   20,   20,   19,   21,   22,   48,   22,
       22,   48,   17,   19,   19,  208,   12,   21,   26,   26,

       41,   22,   41,   23,   43,   23,   23,   22,   28,   28,
      208,   59,   49,   22,   43,   22,   49,   23,   40,   40,
       40,   40,    9,   23,   42,   44,   22,   44,   63,   23,
       50,   42,   45,   22,  434,   42,   44,   47,   42,   51,
       50,   22,   23,   45,   22,   47,   45,   45,   45,   23,
       52,   51,   57,   53,   52,   53,   54,   23,   53,   53,
       71,   57,   79,   79,   54,   59,   72,   53,   53,   53,
       63,   54,   53,   72,   79,   79,   82,   82,  433,  136,
       79,   84,   83,   84,   83,   83,   84,   84,   82,   82,
       98,   85,  127,  136,   82,  127,   83,   85,   71,   79,

       79,   98,   83,   98,  147,   98,   79,  147,   83,   87,
      101,   87,   87,   82,   82,  101,  108,   85,  161,  161,
       82,   83,  108,   87,  116,   85,  134,  123,   83,   87,
      141,  138,  134,  141,  116,   87,   83,  123,  146,  188,
      188,  226,  176,  178,  134,  226,  141,  146,   87,  138,
      176,  155,  432,  155,  322,   87,  155,  155,  157,  157,
      158,  178,  158,   87,  322,  158,  158,  160,  162,  162,
      157,  157,  180,  160,  163,  180,  157,  214,  239,  239,
      163,  162,  243,  243,  300,  214,  162,  300,  227,  314,
      314,  431,  294,  160,  317,  157,  157,  227,  430,  227,

      163,  160,  157,  317,  227,  227,  162,  294,  163,  240,
      240,  241,  162,  241,  246,  429,  241,  241,  244,  244,
      246,  360,  240,  428,  360,  315,  315,  240,  427,  426,
      421,  244,  420,  419,  418,  417,  244,  415,  315,  413,
      246,  412,  411,  315,  410,  409,  408,  240,  246,  407,
      406,  405,  404,  240,  402,  401,  244,  400,  397,  396,
      394,  389,  244,  315,  388,  386,  385,  382,  381,  315,
      436,  436,  436,  436,  436,  436,  436,  437,  437,  438,
      380,  438,  438,  438,  438,  438,  439,  439,  439,  440,
      379,  440,  440,  441,  378,  441,  441,  442,  377,  442,

      443,  443,  376,  443,  443,  375,  374,  373,  372,  371,
      370,  369,  367,  366,  364,  363,  362,  361,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  349,  347,  346,
      345,  344,  343,  341,  340,  339,  338,  337,  335,  333,
      332,  331,  330,  328,  326,  325,  324,  323,  321,  320,
      319,  318,  313,  312,  311,  310,  308,  307,  306,  305,
      304,  303,  302,  301,  299,  298,  297,  296,  295,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  275,  274,  273,  272,
      269,  268,  267,  266,  265,  262,  261,  259,  258,  257,

      256,  255,  254,  253,  252,  251,  249,  248,  247,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  213,  212,  211,  210,  209,  207,  206,  205,  204,
      202,  201,  200,  199,  198,  196,  195,  194,  193,  192,
      191,  190,  189,  187,  186,  185,  184,  183,  182,  181,
      179,  177,  175,  174,  173,  172,  171,  170,  169,  168,
      166,  165,  153,  149,  148,  145,  144,  143,  142,  140,
      139,  137,  135,  133,  132,  131,  130,  129,  128,  126,
      125,  124,  122,  121,  120,  119,  118,  117,  115,  114,

      113,  112,  111,  110,  109,  107,  106,  105,  104,  103,
      102,   99,   97,   96,   95,   93,   90,   88,   67,   65,
       56,   55,   46,   39,   38,   35,   34,   33,   32,   31,
       27,   16,   13,   11,   10,    8,    3,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analyse.l"
/*

     This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
     This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>
***************************************************************************
COBFU, C/C++ obfuscator
Authors & contribute :
	Ryarbyah{
		 Main Authors: 	
		 https://github.com/ryarnyah/AnalyseC
		 C Obfuscator; http://not2do4programing.wordpress.com/
	}
	Khalegh{
		 Continues:
		 https://github.com/khaleghsalehi/COBFU
		 Khalegh Salehi 
        	 Email:khaleghsalehi@gmail.com
	}
Note:	
	[+] Add \ to break the line in c source code			 
*/
#line 39 "analyse.l"
#include <stdio.h>
#include <stdlib.h>
#include "cons.h"
#include <time.h>
#include "list_exist.h"
#include <string.h>
char *parse_akolad();
//char *parse_parantez();
void parse_while();
void count();
void comment();
void newprintf();
void newscanf();
void changedigit();
static list_exist list;
static FILE * currentFile = NULL;
static int isAuto = 1;
static int byPass = 0;
//define global variable for parse_akolad
char buff11[1000];
char polbuff11[1000];
#line 815 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "analyse.l"

#line 1004 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 436 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 638 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "analyse.l"
{ parse_while();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "analyse.l"
{ comment();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "analyse.l"
{ newprintf();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "analyse.l"
{ newscanf();}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "analyse.l"
{ char * reso = malloc(sizeof(char)*(strlen(yytext) + 1)); memcpy(reso, yytext, sizeof(char)*(strlen(yytext) + 1));cons * res = get_from_key(list, reso, isAuto, byPass); fprintf(currentFile, "%s", res->second); if(byPass==1)byPass=0;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "analyse.l"
{fprintf(currentFile, "%s", yytext);byPass=1;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "analyse.l"
{fprintf(currentFile, "%s", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "analyse.l"
{fprintf(currentFile, "%s", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 106 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 107 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 108 "analyse.l"
{ changedigit(); }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 109 "analyse.l"
{ fprintf(currentFile, "%s", "Digit yytext"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "analyse.l"
{ changedigit(); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "analyse.l"
{ changedigit(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 "analyse.l"
{ changedigit(); }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 114 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 124 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 125 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 126 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 127 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 128 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 134 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 135 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 136 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 137 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 141 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 142 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 143 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 144 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 145 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 146 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 147 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 148 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 149 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 150 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 151 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 152 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 154 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 155 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 156 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 158 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 159 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 160 "analyse.l"
{ fprintf(currentFile, "%s", ""); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 161 "analyse.l"
{ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 162 "analyse.l"
{ /* ignore bad characters */ fprintf(currentFile, "%s", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 164 "analyse.l"
ECHO;
	YY_BREAK
#line 1585 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 436 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 436 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 435);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 164 "analyse.l"



int yywrap()
{
 return 1;
}

//zx
void parse_while()
{
int i,arg;
char ako[1]="";
char swname[100]="";
for(i=0;i<=1000;i++)
{
	buff11[i]='\0';
	polbuff11[i]='\0';
}

/**/
/*Creat random name for switch case var*/
char charset[] = "0123456789"
                 "abcdefghijklmnopqrstuvwxyz"
                 "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
char prefix[]="_";
swname[0]=prefix[0];
swname[1]=prefix[0];
i=2;
    while (i<=8) {
        size_t index = (double) rand() / RAND_MAX * (sizeof charset - 1);
        swname[i] =charset[index];
        i++;
    }
    swname[11] ='\0';

for(i=0;i<10;i++)
printf("%c",swname[i]);
/* End name generation */
printf("\n\n");




parse_akolad();
arg=0;
i=0;
strcpy(ako,"{");



// TEMP for test, remove here

i=0;
printf("\n------------------------\n");
for(i=0;i<=15;i++)
	printf("[%d][%c]-",i,polbuff11[i]);
printf("\n------------------------\n");



//TEMP for test
i=0;
while(polbuff11[i]!=ako[0])
{
		printf("%c",polbuff11[i]);
		i++;
		arg++;
}
//
//printf("Index is a -> %d\n",k);
//




fprintf(currentFile,"%s","__OoOoOl1l1l=1;\nwhile(__OoOoOl1l1l!=0){\nswitch(__OoOoOl1l1l)\n{\ncase 1:{__OoOoOl1l1l=2;break;}\ncase 2:\n{");
fprintf(currentFile,"%s","\n\tif");
                       for (i=0;i<=arg-1;i++)
				fprintf(currentFile,"%c",polbuff11[i]);
fprintf(currentFile,"%s","\n\t\t{__OoOoOl1l1l=3;break;}");
fprintf(currentFile,"%s","\n\tif(!"); 
			for(i=0;i<=arg-1;i++)
                        	fprintf(currentFile,"%c",polbuff11[i]);
fprintf(currentFile,"%s" ,")\n\t\t{__OoOoOl1l1l=0;break;}\nbreak;}\ncase 3:\n{\n");


			i=arg+1;
			while(polbuff11[i]!='\0')
//			for (i=arg+1;i<1000;i++)
			{
						fprintf(currentFile,"%c",polbuff11[i]);
						i++;
			}

fprintf(currentFile,"%s","\n\n__OoOoOl1l1l=2;break;}\n}"); // check for removed {, remember
}// End of parse while function.








char *parse_akolad()
{
        char c1;
        while((c1 = input()) !='}')  
        {
		sprintf(buff11,"%c",c1);
		strcat(polbuff11,buff11);		
		parse_akolad();
		return 0;
	}
		strcat(polbuff11,"}");
return polbuff11;
}





/******************************** 
	Remove the comments by //
*********************************/
/*
 How to use gcc preprocessors to remove all comment in c source code 
 gcc -fpreprocessed -dD -E test.c
*/
 
/*Comment by myself*/
void comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0)
		;//putchar(c);

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0)
		;//putchar(c1);
}
/********************************************
********************************************/
void changedigit()
{
float  rp1,rp2,digit;
int rndx;
//float poldigit;
//int poldigit,rndx,rp1,rp2,digit;

//zz
		srand(time(NULL));
		rndx=rand()%10000000+1;
                printf("%d",rndx);
               	digit=atoi(yytext);
		rp1=(digit)-rndx;
       	        rp2=(digit-rp1)+rndx;          
  //     	        poldigit=(rp1+rp2-rndx);
		fprintf(currentFile, "((((%f)+(%f))-((%d))))",rp1,rp2,rndx); // the prantez help to complex exprestion
	//	fprintf(currentFile, "%f+%f-%d",rp1,rp2,rndx); // the prantez help to complex exprestion


}
/********************************************
********************************************/
/*
	START scanf FUNCTION
        
*/
void newscanf()
{
   char c,c1;
   int  code,code2;
   char binstr[1000]="";
   char repo[1000]="",hexrepo[1000]="";
   while ((c=input())!='(' && c !=0)
   unput(c);
   while ((c1=input()) !=',' && c!=0){             
                code=(int)c1;
                if(code==92){ // Find Slash character 
                                         sprintf(hexrepo,"%s","\\");
                                         strcat(repo,hexrepo);
                                         c1=input();//Next
                                         sprintf(hexrepo,"%c",c1);
                                         strcat(repo,hexrepo); 
					 continue;}
                //zz

                if(code==37){ // Find % character & figureout printf format string 
                                         sprintf(hexrepo,"%s","\%");
                                         strcat(repo,hexrepo);
                                         c1=input();//Next 
                                         code2=(int)c1;
                                         while (((int)code2!=100) && ((int)code2!=99) && ((int)code2!=102) && ((int)code2!=115) && ((int)code2!=105) )
                                                {
                                                 sprintf(hexrepo,"%c",c1);
                                                 strcat(repo,hexrepo);
                                                 c1=input();
                                                 code2=(int)c1;
                                                 //continue;
                                                }  
                                         if ( code2==105 || code2==99 || code2==102 || code2==115 || code2==100 )
                                                {
                                                 sprintf(hexrepo,"%c",c1);
                                                 strcat(repo,hexrepo);
                                  //               c1=input();
                                                 continue;
						}

			  } // End of % checkup
     
              if(code!=34){ // Ignore " character 
                                 	sprintf(hexrepo,"\\x%x", c1);
	                                strcat(repo,hexrepo);
                                        } 
  } // End of while II            

sprintf(binstr, "%s%s%s", "scanf(\"",repo,"\",");
fprintf(currentFile, "%s", binstr);   		
printf("%s",yytext);
printf("\n");
}

/*
	END Scanf FUNCTION   
 
*/

/********************************************
********************************************/




/*
	START PRINTF FUNCTION
        printf([message/format specific],variable)
        printf(" [%[Dig].[Dig]f,d,i,c,s,[a-z][A-Z][0-9][!@#$%^&*()_+]",v1,v2,..,v(n-1),v(n))
        Where v1,v2,..,v(n-1),v(n-2) must be changed and replaced.          
 
        
*/



/***********************************

Orginal syntax : 
		printf("[Printf format type/message]",var1,var2,...varn);
So:
		printf(part I,Part II)			
Obfuscation details:
		while(c1=input!=')')
			buff=buff+c1; // buff is a string contain all string befor last ) in printf(.....)
		// Part I	
		index=find-last-str-postion(buff,");
		messagebuff="printf('") 
		for(i=0;i<=index,i++)
			messagebuff=messagebuff+buff[i]
		for(i=0;i<len(messagebuff;i++)
			{
				if(messgebuff[i]<>"\") 
					write(hex(messagebuff[i]));
				else // format type string...
					{
						
						while(messagebuff[i]<> d,s,o,... )
							{
								write(messagebuff[i];
								i++;	 // For example \3.33f
							}	
							write(mesaagebuff[i++?]; / for example \n --> n
					}	
			}
	      for(i=index;i<=len(buff);i++) // write Part II
			write(buff[i]);
	 	write(")");			
This approach have a problem during parsing becuase this example parsing not completely for example printf(" my name is a(a) ",.....
when parsing parse until a) and drop esle... 

************************************/



void newprintf()
{
   char c,c1;
   int  i,code,code2;
   char binstr[1000]="";
   char repo[1000]="",hexrepo[1000]="";
/* 
   CHECK FOR SIMPLE printf, work such as simple echo
   Example:
            printf("Hello World")  
*/


/*
  CHECK FOR ADVANCED printf, 
  Example:
          printf("\n\n%d%3.1f",i,j);     
*/
   for(i=0;i<100;i++)
        printf("%c",yytext[i]);	
   while ((c=input())!='(' && c !=0)
   unput(c);
   while ((c1=input()) !=',' && c!=0){             
                code=(int)c1;
                if(code==92){ // Find Slash character 
                                         sprintf(hexrepo,"%s","\\");
                                         strcat(repo,hexrepo);
                                         c1=input();//Next
                                         sprintf(hexrepo,"%c",c1);
                                         strcat(repo,hexrepo); 
					 continue;}
                //zz

                if(code==37){ // Find % character & figureout printf format string 
                                         sprintf(hexrepo,"%s","\%");
                                         strcat(repo,hexrepo);
                                         c1=input();//Next 
                                         code2=(int)c1;
                                         while (((int)code2!=100) && ((int)code2!=99) && ((int)code2!=102) && ((int)code2!=115) && ((int)code2!=105) )
                                                {
                                                 sprintf(hexrepo,"%c",c1);
                                                 strcat(repo,hexrepo);
                                                 c1=input();
                                                 code2=(int)c1;
                                                 //continue;
                                                }  
                                         if ( code2==105 || code2==99 || code2==102 || code2==115 || code2==100 )
                                                {
                                                 sprintf(hexrepo,"%c",c1);
                                                 strcat(repo,hexrepo);
                                  //               c1=input();
                                                 continue;
						}

			  } // End of % checkup
     
              if(code!=34){ // Ignore " character 
                                 	sprintf(hexrepo,"\\x%x", c1);
	                                strcat(repo,hexrepo);
                                        } 
  } // End of while II            

sprintf(binstr, "%s%s%s", "printf(\"",repo,"\",");
fprintf(currentFile, "%s", binstr);   		
printf("%s",yytext);
printf("\n");
}

/*
	END PRINTF FUNCTION   
 
*/



int column = 0;

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	ECHO;
}

static void usage(char * s)
{
  fprintf(stderr, "Usage: %s [-m(manuel)] <fichier a obfusquer>\n", s);
  exit(1);
}

int main(int argc, char **argv)
{


  if(argc < 2)
    usage(argv[0]);
  list = create();
  int i = 1;
  if(strlen(argv[1]) == 2 && argv[1][1] == 'm')
  {
    isAuto = 0;
    i = 2;
    printf("is not auto");
  }
  for(; i < argc; i++)
  {
    char tmp[strlen(argv[i]) + 2];
    memcpy(tmp, argv[i], sizeof(char)*(strlen(argv[i])));
    tmp[strlen(argv[i])] = '_';
    tmp[strlen(argv[i]) + 1] = '\0';
    currentFile = fopen(tmp, "w");
    if(currentFile == NULL)
    {
	perror("fopen");
	return 1;
    }
    yyin = fopen(argv[i], "r");
    if(yyin == NULL)
    {
	perror("fopen");
	return 1;
    }
    fprintf(currentFile, "#include \"convert.h\"\n");		
	    yylex();
    fclose(currentFile);
    fclose(yyin);
    currentFile = NULL;
    yyin = NULL;
  }
  saveToFile(list, "convert.h");
  delete(list);
  return 0;
}

